### ISSUE TITLE
Adding essential packages for Node.js & Typescript

### ISSUE THREAD

**Issue by codeYann** [codeYann/gen-scape#1]
# Todo

- [ ] Create a new branch.
- [ ] npm init
- [ ] Adding typescript.
- [ ] Setting up tsconfig.
- [ ] Adding packages for Node.js,
- [ ] Adding Typescript packages.
