### ISSUE TITLE
Creating http module

### ISSUE THREAD

**Issue by codeYann** [codeYann/gen-scape#3]
# TODO

- [x] Creating http module
- [x] Creating request class
- [x] Creating an interface for request class
- [x] Creating timeout function
- [x] Creating race time delay function
- [x] Creating get function
- [x] Creating make request function
- [x] Creating first test for request class
- [x] Test make request function
- [x] Create a PR
